name: ci

on:
    push:
        branches: [main]
        paths-ignore:
            - ".vscode/**"
            - "**/*.md"
    pull_request:
        branches: [main]
        paths-ignore:
            - ".vscode/**"
            - "**/*.md"

jobs:
    semver:
        name: Semantic version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Github env
              id: github_env
              env:
                GITHUB_MAIN: ${{ github.ref == 'refs/heads/main' }}
              run: |
                echo "::set-output name=GITHUB_MAIN::${GITHUB_MAIN}"

            - name: Tag version
              id: tag_version
              uses: mathieudutour/github-tag-action@v5.5
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                dry_run: ${{ steps.github_env.outputs.GITHUB_MAIN != 'true' }}
                create_annotated_tag: true
                release_branches: "^main$"

            - name: Calc semver
              id: calc_semver
              env:
                GITHUB_SHA: ${{ github.sha }}
                GITHUB_MAIN: ${{ steps.github_env.outputs.GITHUB_MAIN }}
                SEMVER: ${{ steps.tag_version.outputs.new_version }}
              run: |
                if [ "${GITHUB_MAIN}" = "true" ]; then
                    echo "::set-output name=SEMVER::${SEMVER}"
                else
                    echo "::set-output name=SEMVER::${SEMVER}-${GITHUB_SHA}"
                fi

        outputs:
            GITHUB_MAIN: ${{ steps.github_env.outputs.GITHUB_MAIN }}
            SEMVER: ${{ steps.calc_semver.outputs.SEMVER }}

    build-test:
        name: Build and test
        runs-on: ubuntu-latest
        needs:
            - semver
        env:
            REPONAME: dockman

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: docker build -t ${REPONAME} .

            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              if: ${{ needs.semver.outputs.GITHUB_MAIN == 'true' }}
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Publish images to Docker Hub
              if: ${{ needs.semver.outputs.GITHUB_MAIN == 'true' }}
              env:
                SEMVER: ${{ needs.semver.outputs.SEMVER }}
                USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                docker tag ${REPONAME} ${USERNAME}/${REPONAME}:SEMVER && \
                docker push ${USERNAME}/${REPONAME}:SEMVER" && \
                docker tag ${REPONAME} ${USERNAME}/${REPONAME}:latest && \
                docker push ${USERNAME}/${REPONAME}:latest
